# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 02:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_mycourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mycourses',
            options={'verbose_name': 'My courses', 'verbose_name_plural': 'My courses'},
        ),
    ]
