# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-06 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_auto_20171206_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourses',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='owned', to='courses.Course'),
        ),
    ]
